import { Inter } from 'next/font/google'
import './globals.css'
import FooterComponent from './components/FooterComponent'
import NavBarComponent from './components/NavBarComponent'
import Providers from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <NavBarComponent></NavBarComponent>
          {children}
          <FooterComponent></FooterComponent>
        </Providers>
      </body>
    </html>
  )
}
